apiVersion: apps/v1
kind: Deployment
metadata:
  name: dht-deployment
spec:
  selector:
    matchLabels:
      app: dht
  replicas: 2 # tells deployment to run N pods matching the template
  template:
    metadata:
      labels:
        app: dht
    spec:
      containers:
      - name: dht
        image: dht
        ports:
        - containerPort: 80
