apiVersion: apps/v1
kind: Deployment
metadata:
  name: dht-v1-deployment
  labels:
    app: dht-v1-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dht-v1-app
  template:
    metadata:
      labels:
        app: dht-v1-app
    spec:
      containers:
      - name: dht
        image: dht
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: dht-v1-svc
  labels:
    name: dht-v1-svc
spec:
  selector:
    app: dht-v1-app
  type: LoadBalancer
  ports:
    - port: 8888
      protocol: TCP
      targetPort: 8080